# Generated by Django 2.2.3 on 2019-07-31 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('e_mail', models.EmailField(max_length=254, unique=True)),
                ('skills', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='CodePost',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ets', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ets', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.CodePost')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('ets', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.Comments')),
            ],
        ),
    ]
